<a href="https://colab.research.google.com/github/ThomasPalma1/FatecAPI-Dataset/blob/main/service_recommend.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Análise Exploratória dos Dados

In [242]:
#Importação das bibliotecas ou pacotes
import numpy as pd
import pandas as pd
from sklearn.neighbors import NearestNeighbors

In [243]:
#Importação dos serviços de bancos categorizados
services = pd.read_csv("/content/drive/MyDrive/CSV_IA/Consolidados_serviços_categoria/consolidado_Servicos_categoria_id.csv", encoding="utf-8",sep=";",error_bad_lines=False)

<ipython-input-243-0bf5d5b03764>:2: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  services = pd.read_csv("/content/drive/MyDrive/CSV_IA/Consolidados_serviços_categoria/consolidado_Servicos_categoria_id.csv", encoding="utf-8",sep=";",error_bad_lines=False)

In [244]:
services

,Cnpj,BancoID,RazaoSocial,ValorMaximo,Periodicidade,ListaServiço,Categoria
0,4355489.0,034545104X,COOPERATIVA DE CRÉDITO UNICRED COOMARCA LTDA. ...,"11325,4",A cada 365 dias,Anuidade - cartão básico internacional,Cooperativas de Credito
1,10808037.0,155061224,COOPERATIVA DE CRÉDITO DOS EMPRESÁRIOS DE MANA...,1600,A cada 365 dias,Anuidade - cartão básico internacional,Cooperativas de Credito
2,4833655.0,446520802,COOPERATIVA DE ECONOMIA E CRÉDITO MÚTUO SICOOB...,1540,A cada 365 dias,Anuidade - cartão básico internacional,Cooperativas de Credito
3,37079720.0,052165615X,COOPERATIVA DE CRÉDITO DE LIVRE ADMISSÃO LTDA....,1540,A cada 360 dias,Anuidade - cartão básico internacional,Cooperativas de Credito
4,71479653.0,521795028,COOPERATIVA DE ECONOMIA E CRÉDITO MÚTUO DOS MÉ...,1500,A cada 360 dias,Anuidade - cartão básico internacional,Cooperativas de Credito
...,...,...,...,...,...,...,...
76121,22753982.0,440415316,COOPERATIVA DE CRÉDITO CREDISETE LTDA. - SICOO...,0,-,Venda de moeda estrangeira - espécie,Cooperativas de Credito
76122,22610500.0,8804478152,VORTX DISTRIBUIDORA DE TITULOS E VALORES MOBIL...,0,-,Venda de moeda estrangeira - espécie,Sociedades Distribuidoras...
76123,88471024.0,446516627,COOPERATIVA DE CRÉDITO CENTRO LESTE - SICREDI ...,0,-,Venda de moeda estrangeira - espécie,Cooperativas de Credito
76124,87780284.0,1585420220,"COOPERATIVA DE CRÉDITO, POUPANÇA E INVESTIMENT...",0,-,Venda de moeda estrangeira - espécie,Cooperativas de Credito
76125,87900601.0,3596154170,"COOPERATIVA DE CRÉDITO, POUPANÇA E INVESTIMENT...",0,-,Venda de moeda estrangeira - espécie,Cooperativas de Credito

In [245]:
#Importação dos dados referentes às notas de serviços de bancos
ratings = pd.read_csv("/content/drive/MyDrive/CSV_IA/Consolidados_serviços_categoria/service_ratings_category.csv", sep=";" , encoding="latin-1", error_bad_lines=False)

<ipython-input-245-95bb5dfa5eb4>:2: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  ratings = pd.read_csv("/content/drive/MyDrive/CSV_IA/Consolidados_serviços_categoria/service_ratings_category.csv", sep=";" , encoding="latin-1", error_bad_lines=False)
Skipping line 70560: expected 4 fields, saw 5

Skipping line 164100: expected 4 fields, saw 7
Skipping line 257389: expected 4 fields, saw 6

Skipping line 327537: expected 4 fields, saw 7

Skipping line 420478: expected 4 fields, saw 6
Skipping line 466728: expected 4 fields, saw 5

Skipping line 582091: expected 4 fields, saw 7

Skipping line 742073: expected 4 fields, saw 5
Skipping line 764908: expected 4 fields, saw 6

Skipping line 810577: expected 4 fields, saw 7

Skipping line 993444: expected 4 fields, saw 7

<ipython-input-245-95bb5dfa5eb4>:2: DtypeWarning: Columns (1,2) have mixed types. Specify dtype option on import or set low_memory=False.
  ratings = pd.read_csv("/content/drive/MyDrive/CSV_IA/Consolidados_serviços_categoria/service_ratings_category.csv", sep=";" , encoding="latin-1", error_bad_lines=False)

In [246]:
ratings

         service_id user_id service_rating                      category
0        034545104X  276725              0       Cooperativas de Credito
1        0155061224  276726              5       Cooperativas de Credito
2        0446520802  276727              0       Cooperativas de Credito
3        052165615X  276729              3       Cooperativas de Credito
4        0521795028  276729              6       Cooperativas de Credito
...             ...     ...            ...                           ...
1151006  0451206711  250764            0.0       Cooperativas de Credito
1151007  0451400763  250764            0.0       Cooperativas de Credito
1151008  0451401387  250764            0.0       Cooperativas de Credito
1151009  0451410777  250764            0.0               Bancos privados
1151010  0452264464  250764            8.0  Sociedades Distribuidoras...

[1151011 rows x 4 columns]

Pré processamento de dados

Renomeando colunas

In [247]:
services = services[['Cnpj','BancoID','RazaoSocial','ValorMaximo','ListaServiço','Categoria']]
services.rename(columns = {'Cnpj':'cnpj','BancoID':'service_id','RazaoSocial':'razaosocial','ValorMaximo':'valormaximo','ListaServico':'listaservico','Categoria':'categoria'}, inplace=True)

<ipython-input-247-d1e6b80a207e>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  services.rename(columns = {'Cnpj':'cnpj','BancoID':'service_id','RazaoSocial':'razaosocial','ValorMaximo':'valormaximo','ListaServico':'listaservico','Categoria':'categoria'}, inplace=True)

In [248]:
#Quantidade de ratings por usuários
ratings['user_id'].value_counts()

11676       13601
153662.0     5230
198711.0     5190
278418       4533
76352        4070
            ...
67674           1
67679           1
67689           1
67696           1
245638          1
Name: user_id, Length: 100760, dtype: int64

In [249]:
#serviços com mais de 50 avaliações
qtdavaliacao = ratings['user_id'].value_counts()>50

In [250]:
qtdavaliacao

11676        True
153662.0     True
198711.0     True
278418       True
76352        True
            ...
67674       False
67679       False
67689       False
67696       False
245638      False
Name: user_id, Length: 100760, dtype: bool

In [251]:
#Quantidade de avaliadores com de 50 serviços avaliados
qtdusers = qtdavaliacao[qtdavaliacao].index
print(qtdusers.shape)

(3488,)

In [252]:
qtdusers

Index([   11676, 153662.0, 198711.0,   278418,  '76352',    23768,  '35859',
          35859,    26544,    23902,
       ...
       '221705',  14966.0, '119505', 114581.0, 216100.0, '216386', 122801.0,
        '40647',  '37512', 219321.0],
      dtype='object', length=3488)

In [253]:
#Trazendo notas de usuários que avaliaram mais de 50 serviços
ratings = ratings[ratings['user_id'].isin(qtdusers)]

In [254]:
#Juntando tabelas
rating_with_services= ratings.merge(services, on='service_id')
rating_with_services.head()

,service_id,user_id,service_rating,category,cnpj,razaosocial,valormaximo,ListaServiço,categoria
0,3257200552,276847,5,Sociedades de Crédito e Financiamento e Invest...,60779196.0,"CREFISA S.A.-CREDITO, FINANCIAMENTO E INVESTIM...",240,Anuidade - cartão básico internacional,Sociedades de Crédito e Financiamento e Invest...
1,3257200552,3326,8,Sociedades de Crédito e Financiamento e Invest...,60779196.0,"CREFISA S.A.-CREDITO, FINANCIAMENTO E INVESTIM...",240,Anuidade - cartão básico internacional,Sociedades de Crédito e Financiamento e Invest...
2,3257200552,59971.0,0,Sociedades de Crédito e Financiamento e Invest...,60779196.0,"CREFISA S.A.-CREDITO, FINANCIAMENTO E INVESTIM...",240,Anuidade - cartão básico internacional,Sociedades de Crédito e Financiamento e Invest...
3,3257200552,59971,0,Sociedades de Crédito e Financiamento e Invest...,60779196.0,"CREFISA S.A.-CREDITO, FINANCIAMENTO E INVESTIM...",240,Anuidade - cartão básico internacional,Sociedades de Crédito e Financiamento e Invest...
4,3379015180,276847,0,Cooperativas de Credito,952415.0,COOPERATIVA DE CRÉDITO DE LIVRE ADMISSÃO CREDF...,240,Anuidade - cartão básico internacional,Cooperativas de Credito

In [255]:
#Quantidade de rating de serviços
number_rating = rating_with_services.groupby('ListaServiço')['service_rating'].count().reset_index()

In [256]:
number_rating

                                          ListaServiço  service_rating
0                                    Abertura de conta            3379
1                                  Abertura de crédito            3744
2    Adiant. a deposit., incl. excesso limite de ch...            1946
3               Anuidade - cartão básico internacional            3174
4                    Anuidade - cartão básico nacional            3106
..                                                 ...             ...
126  Utilização de canais de atend. para retirada e...             532
127  Venda de moeda estrangeira - cartão pré-pago -...              82
128  Venda de moeda estrangeira - cartão pré-pago -...             100
129      Venda de moeda estrangeira - cheque de viagem             192
130               Venda de moeda estrangeira - espécie             428

[131 rows x 2 columns]

In [257]:
#Renomeando coluna
number_rating.rename(columns={'service_rating':'number_of_ratings'}, inplace=True)
number_rating

                                          ListaServiço  number_of_ratings
0                                    Abertura de conta               3379
1                                  Abertura de crédito               3744
2    Adiant. a deposit., incl. excesso limite de ch...               1946
3               Anuidade - cartão básico internacional               3174
4                    Anuidade - cartão básico nacional               3106
..                                                 ...                ...
126  Utilização de canais de atend. para retirada e...                532
127  Venda de moeda estrangeira - cartão pré-pago -...                 82
128  Venda de moeda estrangeira - cartão pré-pago -...                100
129      Venda de moeda estrangeira - cheque de viagem                192
130               Venda de moeda estrangeira - espécie                428

[131 rows x 2 columns]

In [258]:
# Junbtando tabela de serviços com os ratings e tabela de quintadad de ratings por serviço
final_rating = rating_with_services.merge(number_rating, on='ListaServiço')
final_rating

,service_id,user_id,service_rating,category,cnpj,razaosocial,valormaximo,ListaServiço,categoria,number_of_ratings
0,3257200552,276847,5,Sociedades de Crédito e Financiamento e Invest...,60779196.0,"CREFISA S.A.-CREDITO, FINANCIAMENTO E INVESTIM...",240,Anuidade - cartão básico internacional,Sociedades de Crédito e Financiamento e Invest...,3174
1,3257200552,3326,8,Sociedades de Crédito e Financiamento e Invest...,60779196.0,"CREFISA S.A.-CREDITO, FINANCIAMENTO E INVESTIM...",240,Anuidade - cartão básico internacional,Sociedades de Crédito e Financiamento e Invest...,3174
2,3257200552,59971.0,0,Sociedades de Crédito e Financiamento e Invest...,60779196.0,"CREFISA S.A.-CREDITO, FINANCIAMENTO E INVESTIM...",240,Anuidade - cartão básico internacional,Sociedades de Crédito e Financiamento e Invest...,3174
3,3257200552,59971,0,Sociedades de Crédito e Financiamento e Invest...,60779196.0,"CREFISA S.A.-CREDITO, FINANCIAMENTO E INVESTIM...",240,Anuidade - cartão básico internacional,Sociedades de Crédito e Financiamento e Invest...,3174
4,3379015180,276847,0,Cooperativas de Credito,952415.0,COOPERATIVA DE CRÉDITO DE LIVRE ADMISSÃO CREDF...,240,Anuidade - cartão básico internacional,Cooperativas de Credito,3174
...,...,...,...,...,...,...,...,...,...,...
112937,073227902X,11676,7,Bancos privados,33644196.0,BANCO FATOR S.A.,0,Financeiro-Remessa de Recursos Edição de Cont....,Bancos privados,44
112938,073361700X,11676,10,Bancos de Desenvolvimento e Investimento,18520834.0,UBS BRASIL BANCO DE INVESTIMENTO S.A.,0,Financeiro-Remessa de Recursos Edição de Cont....,Bancos de Desenvolvimento e Investimento,44
112939,073942730X,11676,0,Sociedades Distribuidoras...,62287735.0,RENASCENCA DISTRIBUIDORA DE TÍTULOS E VALORES ...,0,Financeiro-Remessa de Recursos Edição de Cont....,Sociedades Distribuidoras...,44
112940,073942730X,13273,0,Sociedades Distribuidoras...,62287735.0,RENASCENCA DISTRIBUIDORA DE TÍTULOS E VALORES ...,0,Financeiro-Remessa de Recursos Edição de Cont....,Sociedades Distribuidoras...,44
112941,073944042X,11676,10,Cooperativas de Credito,24610065.0,COOPERATIVA DE CRÉDITO SICOOB IPÊ - SICOOB IPÊ,0,Financeiro-Remessa de Recursos Edição de Cont....,Cooperativas de Credito,44

In [259]:
#Filtrar serviços que tenham pelo menos 50 avaliações
final_rating = final_rating[final_rating['number_of_ratings'] >=50]
final_rating.shape

(112857, 10)

In [260]:
#Eliminar duplicatas de usuarios que avaliaram mesmo serviço varias vezes
final_rating.drop_duplicates(['user_id','ListaServiço'],inplace=True)
final_rating.shape

<ipython-input-260-d12cd7258e32>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_rating.drop_duplicates(['user_id','ListaServiço'],inplace=True)

(47219, 10)

In [261]:
final_rating

,service_id,user_id,service_rating,category,cnpj,razaosocial,valormaximo,ListaServiço,categoria,number_of_ratings
0,3257200552,276847,5,Sociedades de Crédito e Financiamento e Invest...,60779196.0,"CREFISA S.A.-CREDITO, FINANCIAMENTO E INVESTIM...",240,Anuidade - cartão básico internacional,Sociedades de Crédito e Financiamento e Invest...,3174
1,3257200552,3326,8,Sociedades de Crédito e Financiamento e Invest...,60779196.0,"CREFISA S.A.-CREDITO, FINANCIAMENTO E INVESTIM...",240,Anuidade - cartão básico internacional,Sociedades de Crédito e Financiamento e Invest...,3174
2,3257200552,59971.0,0,Sociedades de Crédito e Financiamento e Invest...,60779196.0,"CREFISA S.A.-CREDITO, FINANCIAMENTO E INVESTIM...",240,Anuidade - cartão básico internacional,Sociedades de Crédito e Financiamento e Invest...,3174
3,3257200552,59971,0,Sociedades de Crédito e Financiamento e Invest...,60779196.0,"CREFISA S.A.-CREDITO, FINANCIAMENTO E INVESTIM...",240,Anuidade - cartão básico internacional,Sociedades de Crédito e Financiamento e Invest...,3174
5,3379015180,11676,9,Cooperativas de Credito,952415.0,COOPERATIVA DE CRÉDITO DE LIVRE ADMISSÃO CREDF...,240,Anuidade - cartão básico internacional,Cooperativas de Credito,3174
...,...,...,...,...,...,...,...,...,...,...
112840,3596154170,86583,6,Cooperativas de Credito,87900601.0,"COOPERATIVA DE CRÉDITO, POUPANÇA E INVESTIMENT...",0,Venda de moeda estrangeira - espécie,Cooperativas de Credito,428
112841,3596154170,57449,0,Cooperativas de Credito,87900601.0,"COOPERATIVA DE CRÉDITO, POUPANÇA E INVESTIMENT...",0,Venda de moeda estrangeira - espécie,Cooperativas de Credito,428
112848,342310578X,191720.0,0,Bancos privados,13720915.0,BANCO WESTERN UNION DO BRASIL S.A.,250,Venda de moeda estrangeira - espécie,Bancos privados,428
112851,1585420220,180917.0,0.0,Cooperativas de Credito,87780284.0,"COOPERATIVA DE CRÉDITO, POUPANÇA E INVESTIMENT...",0,Venda de moeda estrangeira - espécie,Cooperativas de Credito,428
112855,044022599X,203844.0,8,Sociedades Distribuidoras...,34666362.0,MONOPÓLIO CORRETORA DE CÂMBIO LTDA.,0,Venda de moeda estrangeira - espécie,Sociedades Distribuidoras...,428

PIVOT - Transpor usuários em colunas

In [262]:
service_pivot = final_rating.pivot_table(columns='user_id',index='ListaServiço',values='service_rating')

In [263]:
service_pivot

user_id,183,243,254,392,507,626,638,643,741,882,...,98647,98686,98723,98741,98758,98787,98904,99032,99347,99955
ListaServiço,,,,,,,,,,,,,,,,,,,,,
Abertura de conta,NaN,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
Abertura de crédito,NaN,0.0,0.0,NaN,NaN,NaN,0.0,NaN,0.0,NaN,...,NaN,9.0,7.0,0.0,0.0,0.0,NaN,0.0,0.0,10.0
"Adiant. a deposit., incl. excesso limite de ch. Especial",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN
Anuidade - cartão básico internacional,NaN,NaN,0.0,10.0,NaN,NaN,NaN,9.0,NaN,NaN,...,NaN,NaN,NaN,0.0,NaN,NaN,5.0,NaN,NaN,NaN
Anuidade - cartão básico nacional,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,10.0,...,NaN,9.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Utilização de canais de atend. para retirada em espécie - no país,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,7.0,NaN,NaN,NaN,NaN,NaN
Venda de moeda estrangeira - cartão pré-pago - emissão e carga,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Venda de moeda estrangeira - cartão pré-pago - recarga,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN
Venda de moeda estrangeira - cheque de viagem,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Venda de moeda estrangeira - espécie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,NaN

In [264]:
service_pivot.shape

(129, 3473)

In [265]:
from sqlalchemy.sql.base import InPlaceGenerative
service_pivot.fillna(0,inplace=True)

In [266]:
service_pivot

user_id,183,243,254,392,507,626,638,643,741,882,...,98647,98686,98723,98741,98758,98787,98904,99032,99347,99955
ListaServiço,,,,,,,,,,,,,,,,,,,,,
Abertura de conta,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Abertura de crédito,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,9.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0
"Adiant. a deposit., incl. excesso limite de ch. Especial",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Anuidade - cartão básico internacional,0.0,0.0,0.0,10.0,0.0,0.0,0.0,9.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0
Anuidade - cartão básico nacional,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,...,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Utilização de canais de atend. para retirada em espécie - no país,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0
Venda de moeda estrangeira - cartão pré-pago - emissão e carga,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Venda de moeda estrangeira - cartão pré-pago - recarga,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Venda de moeda estrangeira - cheque de viagem,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Venda de moeda estrangeira - espécie,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [267]:
from scipy.sparse import csr_matrix
service_sparce = csr_matrix(service_pivot)

Criação Maquina Preditiva - KNN

In [268]:
from sklearn.neighbors import NearestNeighbors
model = NearestNeighbors(algorithm='brute')
model.fit(service_sparce)

NearestNeighbors(algorithm='brute')

Predições

In [269]:
service_pivot.head()

user_id,183,243,254,392,507,626,638,643,741,882,...,98647,98686,98723,98741,98758,98787,98904,99032,99347,99955
ListaServiço,,,,,,,,,,,,,,,,,,,,,
Abertura de conta,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Abertura de crédito,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,9.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0
"Adiant. a deposit., incl. excesso limite de ch. Especial",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Anuidade - cartão básico internacional,0.0,0.0,0.0,10.0,0.0,0.0,0.0,9.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0
Anuidade - cartão básico nacional,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,...,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0

In [270]:
#Abertura de conta
distances, suggestions = model.kneighbors(service_pivot.iloc[0,:].values.reshape(1,-1))

In [271]:
for i in range(len(suggestions)):
  print(service_pivot.index[suggestions[i]])

Index(['Abertura de conta',
       'Exportação Edição de Contrato de Câmbio via Internet',
       'Venda de moeda estrangeira - cartão pré-pago - recarga',
       'Importação Demais Tarifas (Não incluem despesas no Exteior)',
       'Venda de moeda estrangeira - cartão pré-pago - emissão e carga'],
      dtype='object', name='ListaServiço')

In [272]:
#Anuidade cartão
distances, suggestions = model.kneighbors(service_pivot.iloc[3,:].values.reshape(1,-1))

In [273]:
for i in range(len(suggestions)):
  print(service_pivot.index[suggestions[i]])

Index(['Anuidade - cartão básico internacional',
       'Fornec. de 2ª via de cartão com função mov. conta de poupança',
       'Fornecimento de cópia de microfilme, microficha ou assemelhado',
       'Venda de moeda estrangeira - cheque de viagem',
       'Venda de moeda estrangeira - cartão pré-pago - emissão e carga'],
      dtype='object', name='ListaServiço')

In [274]:
distances, suggestions = model.kneighbors(service_pivot.iloc[10,:].values.reshape(1,-1))

In [275]:
for i in range(len(suggestions)):
  print(service_pivot.index[suggestions[i]])

Index(['CHEQUE - Cheque Visado',
       'Exportação Edição de Contrato de Câmbio via Internet',
       'Venda de moeda estrangeira - cartão pré-pago - emissão e carga',
       'Venda de moeda estrangeira - cartão pré-pago - recarga',
       'Cartão multiplo adicional-intern.-anuidade do contrato'],
      dtype='object', name='ListaServiço')